name: Vul Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
        with:
          path: DongTai-agent-python
      - name: Clone Vul Repository
        uses: actions/checkout@v2
        with:
          repository: jinghao1/DockerVulspace
          ref: main
          path: DockerVulspace

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Prepare Agent code
        run: |
          cd ${{ github.workspace }}/DockerVulspace
          cp -r ${{ github.workspace }}/DongTai-agent-python/dongtai_agent_python ./dongtai_agent_python

      - name: Prepare Agent Config
        shell: python
        run: |
          import json
          filename = '${{ github.workspace }}/DockerVulspace/dongtai_agent_python/config.json'
          with open(filename) as f:
              data = json.load(f)
          data['debug'] = True
          data['iast']['server']['token'] = '0f0025dff8311467f6da5b5109a469f1831aa782'
          data['iast']['server']['url'] = 'http://a28754cd66991441d8d682808caecead-626172336.cn-north-1.elb.amazonaws.com.cn:8000'
          data['project']['name'] = 'Python-DockerVulspace'
          with open(filename, 'w') as f:
              json.dump(data, f)

      - name: Run Vul Container
        env:
          PROJECT_VERSION: 'v1.0.${{ github.run_id }}'
        run: |
          cd ${{ github.workspace }}/DockerVulspace
          docker-compose up -d

      - name: Run Vul test
        run: |
          curl --fail --retry-delay 10 --retry 30 --retry-connrefused http://127.0.0.1:8003/api/django/demo/get_open?name=Data
          cd ${{ github.workspace }}/DockerVulspace
          docker-compose logs djangoweb flaskweb
          bash ${{ github.workspace }}/DongTai-agent-python/dongtai_agent_python/tests/vul-test.sh http://127.0.0.1:8003 ${{ github.run_id }}
          docker-compose logs djangoweb flaskweb
